<?php

return [
    'AX' => [
        'Ada Lovelace',
        'Amahle, Asgarthan Outcast',
        'Amelia Earhart',
        'Anansi',
        'Athena',
        'Axiom Salvager',
        'Axiom Scrambler',
        'Baku',
        'Bravos Rescuer',
        'Bravos Tracer',
        'Bravos Vanguard',
        'Coppélia',
        'Daring Porter',
        'Daughter of Yggdrasil',
        'Dr. Frankenstein',
        'Flawed Prototype',
        'Foundry Armorer',
        'Foundry Engineer',
        'Foundry Mechanic',
        'Ganesha',
        'Gibil',
        'Haven Bouncer',
        'Hound',
        'Inari',
        'Jeanne d\'Arc',
        'Jian, Assembly Overseer',
        'Kelon Elemental',
        'Lord Kelvin',
        'Lyra Chronicler',
        'Magpeng Hoarder',
        'Martengale',
        'Monolith Rune-Scribe',
        'Moonlight Jellyfish',
        'Moth Larva',
        'Mowgli',
        'Muna Druid',
        'Muna Merchant',
        'Nisse',
        'Ogun',
        'Ouroboros Croupier',
        'Ouroboros Inkcaster',
        'Repotter Otter',
        'Rocket Puffin',
        'Skadi',
        'The Frog Prince',
        'The Little Match Girl',
        'The Machine in the Ice',
        'Three Little Pigs',
        'Tinker Bell',
        'Vaike, Energy Pioneer',
        'Vishvakarma',
        'Walrus Scout',
        'Yzmir Stargazer',
    ],
    'BR' => [
        'Achilles',
        'Aja',
        'Akhlut',
        'Amarok',
        'Aroro, Savior of Asgartha',
        'Asmodeus',
        'Atlas',
        'Axiom Salvager',
        'Belasenka',
        'Benzaiten',
        'Bravos Bladedancer',
        'Bravos Pathfinder',
        'Bravos Rescuer',
        'Bravos Tracer',
        'Bravos Trailblazer',
        'Bravos Vanguard',
        'Chiron',
        'Demeter',
        'Dorothy Gale',
        'Dracaena',
        'Eros',
        'Fire Rabbit',
        'Foundry Armorer',
        'Gericht, Revered Duelist',
        'Haven Bouncer',
        'Haven Seiringar',
        'Haven Trainee',
        'Haven Warrior',
        'Hua Mulan',
        'Issun-bōshi',
        'Kaibara, Asgarthan Leviathan',
        'Kappa',
        'Kitsune',
        'Lady of the Lake',
        'Leshy',
        'Lyra Navigator',
        'Mighty Jinn',
        'Mighty Simbi',
        'Ordis Spy',
        'Ouroboros Trickster',
        'Ozma',
        'Parvati',
        'Ratatoskr',
        'Red',
        'Sakarabru',
        'Saskia, Sly Naturalist',
        'Shenlong',
        'Skadi',
        'Son of Yggdrasil',
        'Sun Wukong',
        'Tanuki',
        'The Council',
        'The Hatter',
        'The Little Match Girl',
        'The Snowman',
        'Three Little Pigs',
        'Tiny Jinn',
        'Tomoe Gozen',
        'Tooth Fairy',
        'Valemon',
        'Yeti',
    ],
    'LY' => [
        'Alice',
        'Aloe Vera',
        'Amahle, Asgarthan Outcast',
        'Anansi',
        'Asmodeus',
        'Bravos Pathfinder',
        'Bravos Trailblazer',
        'Cernunnos',
        'Coniferal Coneman',
        'Dr. Frankenstein',
        'Esmeralda',
        'Flamel',
        'Gericht, Revered Duelist',
        'Hathor',
        'Haven Seiringar',
        'Heimdall',
        'Hydracaena',
        'Kadigiran Mage-Dancer',
        'Kaibara, Asgarthan Leviathan',
        'Kappa',
        'Kodama',
        'Loki',
        'Lyra Chronicler',
        'Lyra Cloth Dancer',
        'Lyra Navigator',
        'Lyra Skald',
        'Lyra Thespian',
        'Magpeng Hoarder',
        'Martengale',
        'Mighty Jinn',
        'Nisse',
        'Nyala, Gifted Conjurer',
        'Ordis Nightwarden',
        'Ouroboros Croupier',
        'Ouroboros Inkcaster',
        'Ouroboros Trickster',
        'Pamola',
        'Paper Herald',
        'Persephone',
        'Robin Hood',
        'Santa Claus',
        'Shenlong',
        'Snowball Commando',
        'Studious Disciple',
        'Tanuki',
        'The Hatter',
        'The Sandman',
        'The Snowman',
        'Tinker Bell',
        'Tomoe Gozen',
        'Will-o\'-the-Wisp',
        'Yong-Su, Verdant Weaver',
    ],
    'MU' => [
        'Aja',
        'Akhlut',
        'Aloe Vera',
        'Axiom Scrambler',
        'Cernunnos',
        'Chiron',
        'Coniferal Coneman',
        'Coppélia',
        'Daughter of Yggdrasil',
        'Demeter',
        'Dong Da Shen',
        'Dracaena',
        'Ebenezer Scrooge',
        'Eros',
        'Esmeralda',
        'Flawed Prototype',
        'Ganesha',
        'Hydracaena',
        'Inari',
        'Issun-bōshi',
        'Jack Frost',
        'Kakoba, Legion Commander',
        'Kelon Elemental',
        'Kitsune',
        'Kodama',
        'Leshy',
        'Loki',
        'Lord Kelvin',
        'Lyra Cloth Dancer',
        'Lyra Thespian',
        'Mighty Simbi',
        'Mowgli',
        'Muna Caregiver',
        'Muna Druid',
        'Muna Merchant',
        'Ogun',
        'Ordis Gatekeeper',
        'Ordis Liaison',
        'Parvati',
        'Persephone',
        'Quetzalcóatl',
        'Repotter Otter',
        'Santa Claus',
        'Saskia, Sly Naturalist',
        'Sneezer Shroom',
        'Snoozer Shroom',
        'Son of Yggdrasil',
        'Spindle Harvesters',
        'Sun Wukong',
        'The Machine in the Ice',
        'The Snow Maiden',
        'Tiny Jinn',
        'Verdantback',
        'Walrus Scout',
        'Will-o\'-the-Wisp',
        'Yeti',
        'Yong-Su, Verdant Weaver',
    ],
    'OR' => [
        'Achilles',
        'Amelia Earhart',
        'Anubis',
        'Athena',
        'Atlas',
        'Baba Yaga',
        'Benzaiten',
        'Chrysalis',
        'Dong Da Shen',
        'Ebenezer Scrooge',
        'Fire Rabbit',
        'Foundry Engineer',
        'Foundry Mechanic',
        'Gibil',
        'Haven Trainee',
        'Haven Warrior',
        'Heimdall',
        'Hound',
        'Issitoq',
        'Jack Frost',
        'Jeanne d\'Arc',
        'Jian, Assembly Overseer',
        'Kadigiran Alchemist',
        'Kakoba, Legion Commander',
        'Kuwat, the Dissenter',
        'Monolith Archivist',
        'Monolith Legate',
        'Monolith Rune-Scribe',
        'Ordis Attorney',
        'Ordis Cadets',
        'Ordis Gatekeeper',
        'Ordis Liaison',
        'Ordis Nightwarden',
        'Ordis Overseer',
        'Ordis Spy',
        'Ordis Trooper',
        'Ozma',
        'Paper Herald',
        'Quetzalcóatl',
        'Ratatoskr',
        'Robin Hood',
        'Snoozer Shroom',
        'Sunisa, Dedicated Ensign',
        'The Council',
        'The Frog Prince',
        'The Kraken',
        'The Sandman',
        'The Snow Maiden',
        'The Snow Queen',
        'Thoth',
        'Valemon',
        'Verdantback',
        'Vishvakarma',
    ],
    'YZ' => [
        'Ada Lovelace',
        'Alice',
        'Amarok',
        'Anubis',
        'Aroro, Savior of Asgartha',
        'Baba Yaga',
        'Baku',
        'Belasenka',
        'Bravos Bladedancer',
        'Chrysalis',
        'Daring Porter',
        'Dorothy Gale',
        'Flamel',
        'Hathor',
        'Hua Mulan',
        'Issitoq',
        'Kadigiran Alchemist',
        'Kadigiran Mage-Dancer',
        'Kuwat, the Dissenter',
        'Lady of the Lake',
        'Lyra Skald',
        'Monolith Archivist',
        'Monolith Legate',
        'Moonlight Jellyfish',
        'Moth Larva',
        'Muna Caregiver',
        'Nyala, Gifted Conjurer',
        'Ordis Attorney',
        'Ordis Cadets',
        'Ordis Overseer',
        'Ordis Trooper',
        'Pamola',
        'Red',
        'Rocket Puffin',
        'Sakarabru',
        'Sneezer Shroom',
        'Snowball Commando',
        'Spindle Harvesters',
        'Studious Disciple',
        'Sunisa, Dedicated Ensign',
        'The Kraken',
        'The Snow Queen',
        'Thoth',
        'Tooth Fairy',
        'Vaike, Energy Pioneer',
        'Yzmir Stargazer',
    ],
];
