<?php

return [
    'AX' => [
        'The Machine in the Ice',
        'Rocket Puffin',
        'The Little Match Girl',
        'Vaike, Energy Pioneer',
        'Walrus Scout',
        'Daring Porter',
        'Flawed Prototype',
        'Vishvakarma',
        'Gibil',
        'Lord Kelvin',
        'Skadi',
        'Bravos Rescuer',
        'Magpeng Hoarder',
        'Nisse',
        'Repotter Otter',
        'Hound',
        'Moth Larva',
        'Kelon Elemental',
        'Foundry Engineer',
        'Ogun',
        'Foundry Mechanic',
        'Axiom Salvager',
        'Tinker Bell',
        'Jian, Assembly Overseer',
        'Amelia Earhart',
        'Three Little Pigs',
        'Ada Lovelace',
        'Coppélia',
        'Axiom Scrambler',
        'Foundry Armorer',
        'Dr. Frankenstein',
        'Athena',
        'Ganesha',
        'Bravos Tracer',
        'Bravos Vanguard',
        'Haven Bouncer',
        'Martengale',
        'Ouroboros Inkcaster',
        'Anansi',
        'Lyra Chronicler',
        'Ouroboros Croupier',
        'Amahle, Asgarthan Outcast',
        'Mowgli',
        'Inari',
        'Daughter of Yggdrasil',
        'Muna Druid',
        'Muna Merchant',
        'Monolith Rune-Scribe',
        'The Frog Prince',
        'Jeanne d\'Arc',
        'Moonlight Jellyfish',
        'Yzmir Stargazer',
        'Baku',
    ],
    'MU' => [
        'The Machine in the Ice',
        'Walrus Scout',
        'Flawed Prototype',
        'Lord Kelvin',
        'Akhlut',
        'Eros',
        'Will-o\'-the-Wisp',
        'Santa Claus',
        'Jack Frost',
        'Snoozer Shroom',
        'Persephone',
        'Repotter Otter',
        'Saskia, Sly Naturalist',
        'Yeti',
        'Mighty Simbi',
        'Leshy',
        'The Snow Maiden',
        'Demeter',
        'Dong Da Shen',
        'Ebenezer Scrooge',
        'Ordis Liaison',
        'Kelon Elemental',
        'Ogun',
        'Coppélia',
        'Axiom Scrambler',
        'Ganesha',
        'Issun-bōshi',
        'Tiny Jinn',
        'Chiron',
        'Sun Wukong',
        'Lyra Thespian',
        'Esmeralda',
        'Lyra Cloth Dancer',
        'Loki',
        'Muna Caregiver',
        'Kitsune',
        'Spindle Harvesters',
        'Mowgli',
        'Sneezer Shroom',
        'Kodama',
        'Yong-Su, Verdant Weaver',
        'Inari',
        'Daughter of Yggdrasil',
        'Muna Druid',
        'Cernunnos',
        'Dracaena',
        'Aloe Vera',
        'Aja',
        'Parvati',
        'Verdantback',
        'Coniferal Coneman',
        'Son of Yggdrasil',
        'Hydracaena',
        'Muna Merchant',
        'Ordis Gatekeeper',
        'Kakoba, Legion Commander',
        'Quetzalcóatl',
    ],
    'YZ' => [
        'Rocket Puffin',
        'Vaike, Energy Pioneer',
        'Daring Porter',
        'Amarok',
        'Snowball Commando',
        'Nyala, Gifted Conjurer',
        'Ordis Overseer',
        'Sunisa, Dedicated Ensign',
        'Moth Larva',
        'Chrysalis',
        'Pamola',
        'Belasenka',
        'Aroro, Savior of Asgartha',
        'The Snow Queen',
        'Ada Lovelace',
        'Red',
        'Hua Mulan',
        'Bravos Bladedancer',
        'Hathor',
        'Lyra Skald',
        'Muna Caregiver',
        'Spindle Harvesters',
        'Sneezer Shroom',
        'Ordis Trooper',
        'Ordis Cadets',
        'Monolith Legate',
        'Monolith Archivist',
        'Ordis Attorney',
        'Issitoq',
        'Anubis',
        'Thoth',
        'Studious Disciple',
        'Moonlight Jellyfish',
        'Tooth Fairy',
        'Kadigiran Mage-Dancer',
        'Yzmir Stargazer',
        'Lady of the Lake',
        'Baku',
        'Baba Yaga',
        'Kadigiran Alchemist',
        'Alice',
        'Flamel',
        'Kuwat, the Dissenter',
        'Dorothy Gale',
        'The Kraken',
        'Sakarabru',
    ],
    'BR' => [
        'The Little Match Girl',
        'Fire Rabbit',
        'Skadi',
        'Haven Seiringar',
        'Bravos Trailblazer',
        'Bravos Rescuer',
        'Gericht, Revered Duelist',
        'Akhlut',
        'Amarok',
        'Eros',
        'The Snowman',
        'Saskia, Sly Naturalist',
        'Yeti',
        'Mighty Simbi',
        'Leshy',
        'Demeter',
        'Valemon',
        'Benzaiten',
        'Belasenka',
        'Aroro, Savior of Asgartha',
        'Axiom Salvager',
        'Three Little Pigs',
        'Foundry Armorer',
        'Ratatoskr',
        'Issun-bōshi',
        'Tiny Jinn',
        'Bravos Tracer',
        'Bravos Pathfinder',
        'Haven Trainee',
        'Red',
        'Chiron',
        'Hua Mulan',
        'Kappa',
        'Bravos Vanguard',
        'Haven Bouncer',
        'Bravos Bladedancer',
        'Haven Warrior',
        'Sun Wukong',
        'Mighty Jinn',
        'Atlas',
        'Achilles',
        'Shenlong',
        'Tomoe Gozen',
        'Kaibara, Asgarthan Leviathan',
        'Ouroboros Trickster',
        'Tanuki',
        'Lyra Navigator',
        'The Hatter',
        'Asmodeus',
        'Kitsune',
        'Dracaena',
        'Aja',
        'Parvati',
        'Son of Yggdrasil',
        'Ozma',
        'The Council',
        'Ordis Spy',
        'Tooth Fairy',
        'Lady of the Lake',
        'Dorothy Gale',
        'Sakarabru',
    ],
    'OR' => [
        'Vishvakarma',
        'Gibil',
        'Fire Rabbit',
        'Heimdall',
        'Jack Frost',
        'Snoozer Shroom',
        'The Snow Maiden',
        'Hound',
        'Ordis Overseer',
        'Dong Da Shen',
        'Ordis Nightwarden',
        'Ebenezer Scrooge',
        'Sunisa, Dedicated Ensign',
        'Valemon',
        'Ordis Liaison',
        'Benzaiten',
        'Chrysalis',
        'The Snow Queen',
        'Foundry Engineer',
        'Foundry Mechanic',
        'Jian, Assembly Overseer',
        'Amelia Earhart',
        'Athena',
        'Ratatoskr',
        'Haven Trainee',
        'Haven Warrior',
        'Atlas',
        'Achilles',
        'The Sandman',
        'Verdantback',
        'Paper Herald',
        'Ordis Trooper',
        'Ordis Cadets',
        'Monolith Rune-Scribe',
        'Monolith Legate',
        'The Frog Prince',
        'Monolith Archivist',
        'Ozma',
        'The Council',
        'Ordis Gatekeeper',
        'Ordis Spy',
        'Kakoba, Legion Commander',
        'Ordis Attorney',
        'Jeanne d\'Arc',
        'Quetzalcóatl',
        'Issitoq',
        'Anubis',
        'Robin Hood',
        'Thoth',
        'Baba Yaga',
        'Kadigiran Alchemist',
        'Kuwat, the Dissenter',
        'The Kraken',
    ],
    'LY' => [
        'Haven Seiringar',
        'Bravos Trailblazer',
        'Gericht, Revered Duelist',
        'Magpeng Hoarder',
        'Snowball Commando',
        'The Snowman',
        'Nyala, Gifted Conjurer',
        'Will-o\'-the-Wisp',
        'Nisse',
        'Santa Claus',
        'Heimdall',
        'Persephone',
        'Ordis Nightwarden',
        'Pamola',
        'Tinker Bell',
        'Dr. Frankenstein',
        'Bravos Pathfinder',
        'Kappa',
        'Mighty Jinn',
        'Shenlong',
        'Tomoe Gozen',
        'Kaibara, Asgarthan Leviathan',
        'Martengale',
        'Lyra Thespian',
        'Ouroboros Trickster',
        'Hathor',
        'Lyra Skald',
        'Tanuki',
        'Ouroboros Inkcaster',
        'Esmeralda',
        'Lyra Navigator',
        'Anansi',
        'Lyra Cloth Dancer',
        'The Sandman',
        'Lyra Chronicler',
        'Ouroboros Croupier',
        'The Hatter',
        'Amahle, Asgarthan Outcast',
        'Asmodeus',
        'Loki',
        'Kodama',
        'Yong-Su, Verdant Weaver',
        'Cernunnos',
        'Aloe Vera',
        'Coniferal Coneman',
        'Hydracaena',
        'Paper Herald',
        'Robin Hood',
        'Studious Disciple',
        'Kadigiran Mage-Dancer',
        'Alice',
        'Flamel',
    ],
];
